### ISSUE TITLE
tweaking performance: runner vs robot tdb

### ISSUE THREAD

**Issue by wdduncan** [balhoff/blazegraph-runner#19]
I've been experimenting with comparing queries against the NCIT using both runner and robot query with the `--tdb true --keep-tdb-mappings true" options.  

So, far robot is doing much better. 30%-50% faster on average.  

I'm attaching the hacky makefile I used for testing. You can run with `make -f test-blazegraph-runner.txt run-tests`.

Although you may need to run multiple times.  

Are there any tweaks to blazegraph-runner to improve performance?

[test-blazegraph-runner.txt](https://github.com/balhoff/blazegraph-runner/files/4417293/test-blazegraph-runner.txt)

**Comment by balhoff** [comment]
I guess I'll close this since these are probably inherent differences between Blazegraph and Jena TDB. I do think it would be cool to have the same CLI as blazegraph-runner be available for multiple backends.
