### ISSUE TITLE
multiple loads of the same ontology file into the same journal grow the journal each time

### ISSUE THREAD

**Issue by bgood-d4c** [balhoff/blazegraph-runner#28]
I would guess this is an issue with how blazegraph makes/handles bnodes used in ontology files.  I'm not sure its an issue with your code or not, but it surprised me so thought I'd let you know.

Example:
>blazegraph-runner load --journal=mondo_reasoner.jnl --use-ontology-graph=true --informat=rdfxml mondo_reasoned.owl

I get a file with size 418906112 
running the same command again, the file increases to 817823744
and produces slightly different results when running SPARQL queries over logical definitions and the subClassOf* graph.  (mondo_reasoned.owl is the output of robot reason on mondo.owl from a few months ago)

**Comment by balhoff** [comment]
I think this is working as it should. Every time you load an RDF file containing bnodes, they will all be fresh nodes in the triplestore. Otherwise you could end up with unintended unification nodes from different files. The safest thing would be to delete the graph beforehand.
