### ISSUE TITLE
Importing process hangs for some big data

### ISSUE THREAD

**Issue by yy20716** [balhoff/blazegraph-runner#6]
Hello, I am experiencing a weird error when trying to importing data using the blazegraph-runner. 
   * I tried to import a number of different ttl data from this repository (https://data.monarchinitiative.org/ttl/) using the load command provided by this program. Importing small datasets was perfectly fine but sometimes importing big datasets is not working, i.e. the program hanged without any other error messages. This issue "sometimes" happens, e.g., around 5 or 6 times of 10.

  * I ran this program using sbt shell, e.g., "> run --properties=src/main/resources/org/renci/blazegraph/blazegraph.properties load go.ttl"

  * I initially doubted that the data itself might be wrong but importing using load command provided by Blazegraph's admin webpage (https://wiki.blazegraph.com/wiki/index.php/Quick_Start#Load_Data) worked without any errors, e.g., "load <file:///home/yy20716/blazegraph-runner/go.ttl>". I also tested data with other triplestores such as Stardog community editions, so the data itself seems okay. 

Could you please let me know what I should try to solve this issue? Is there any options or configurations I can adjust to see what happens behind? Thank you.

**Comment by balhoff** [comment]
You may want to build the command line tool first and then run separately from sbt. You can do that via `sbt stage`. Then run `./target/universal/stage/bin/blazegraph-runner`. Or you could download a [pre-built release](https://github.com/balhoff/blazegraph-runner/releases)—but I think the unreleased code has better error reporting.

Before running, increase the memory by setting an environment variable: `export JAVA_OPTS=-Xmx32G`.

Please let me know if these ideas work for you.

**Comment by yy20716** [comment]
* Apologies for a late response. I tried based on your suggestion (i.e. sbt stage) and it magically worked this time. Thank you so much.
